# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnmain', '0002_auto_20180927_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='alt',
            new_name='picture_title',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='position',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
