# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnmain', '0003_auto_20180927_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture_title',
            new_name='alt',
        ),
        migrations.AddField(
            model_name='picture',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default='picture', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
