# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnmain', '0004_auto_20180927_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gnmain.Category'),
        ),
    ]
